version: "3.9"
networks:
  cassandra:
services:
  cass1:
    build:
      context: build
#    image: cassandra:3.11.4
#    entrypoint: ["/start.sh"]
    container_name: cass1
    hostname: cass1
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./etc_cassandra-3.11.4_vanilla:/etc_cassandra_orig
      - ./start.sh:/start.sh
      - ./docker-entry.sh:/usr/local/bin/docker-entrypoint.sh
    environment: &environment
        CASSANDRA_SEEDS: "cass1,cass2"    # The first two nodes will be seeds
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
        CASSANDRA_CONFIG: /etc/cassandra/

  cass2:
    build:
      context: build
    #image: cassandra:3.11.4
    #entrypoint: ["/start.sh"]
    container_name: cass2
    hostname: cass2
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9043:9042"
    volumes:
      - ./etc_cassandra-3.11.4_vanilla:/etc_cassandra_orig
      - ./start.sh:/start.sh
      - ./docker-entry.sh:/usr/local/bin/docker-entrypoint.sh
    environment: *environment

  cass3:
    build:
      context: build
    #image: cassandra:3.11.4
    #entrypoint: ["/start.sh"]
    container_name: cass3
    hostname: cass3
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9044:9042"
    volumes:
      - ./etc_cassandra-3.11.4_vanilla:/etc_cassandra_orig
      - ./start.sh:/start.sh
      - ./docker-entry.sh:/usr/local/bin/docker-entrypoint.sh
    environment: *environment
